// <auto-generated />
using System;
using GamingReport.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingReport.Infra.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("GamingReport.Core.Reviews.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GamePlatform")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Score")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UpPoints")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = "085b2794-d434-4acf-9bee-2b476906fd1f",
                            Content = "Content for Review One",
                            CreatedAt = new DateTime(2025, 3, 20, 16, 26, 25, 450, DateTimeKind.Local).AddTicks(631),
                            DownPoints = 2,
                            GameId = "2244383b-50d4-47aa-96c1-d1a59ecf47d9",
                            GamePlatform = 0,
                            Score = 8.5m,
                            Title = "Review One",
                            UpPoints = 10
                        },
                        new
                        {
                            Id = "39617810-2fc0-4845-8ee6-c53b1f19d343",
                            Content = "Content for Review Two",
                            CreatedAt = new DateTime(2025, 3, 20, 16, 26, 25, 450, DateTimeKind.Local).AddTicks(689),
                            DownPoints = 1,
                            GameId = "95354d6e-9e98-4f07-a60c-984b6051948f",
                            GamePlatform = 0,
                            Score = 9.0m,
                            Title = "Review Two",
                            UpPoints = 15
                        });
                });

            modelBuilder.Entity("GamingReport.Core._Developer.Developer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = "f77b48d0-d04d-43cc-9138-be13a43f24e4",
                            Name = "Developer One"
                        },
                        new
                        {
                            Id = "04edaa65-cd88-41dd-9388-0e12e9d53123",
                            Name = "Developer Two"
                        });
                });

            modelBuilder.Entity("GamingReport.Core._Game.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeveloperId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = "2244383b-50d4-47aa-96c1-d1a59ecf47d9",
                            Description = "Description for Game One",
                            DeveloperId = "f77b48d0-d04d-43cc-9138-be13a43f24e4",
                            Name = "Game One",
                            Platform = "[0,2]"
                        },
                        new
                        {
                            Id = "95354d6e-9e98-4f07-a60c-984b6051948f",
                            Description = "Description for Game Two",
                            DeveloperId = "04edaa65-cd88-41dd-9388-0e12e9d53123",
                            Name = "Game Two",
                            Platform = "[1,3]"
                        });
                });

            modelBuilder.Entity("GamingReport.Core.Reviews.Review", b =>
                {
                    b.HasOne("GamingReport.Core._Game.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamingReport.Core._Game.Game", b =>
                {
                    b.HasOne("GamingReport.Core._Developer.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("GamingReport.Core._Developer.Developer", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
